# Generated by Django 5.1 on 2024-10-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_pdfdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
